# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  acer-predator-turbo-and-rgb-keyboard-linux-module = {
    pname = "acer-predator-turbo-and-rgb-keyboard-linux-module";
    version = "6eafee25668cf2ffb8a79fd376a638e9ca4dc6db";
    src = fetchFromGitHub {
      owner = "JafarAkhondali";
      repo = "acer-predator-turbo-and-rgb-keyboard-linux-module";
      rev = "6eafee25668cf2ffb8a79fd376a638e9ca4dc6db";
      fetchSubmodules = false;
      sha256 = "sha256-TGBo9GxVJ74mOnqpkjZRFk0e7XiT6iZbVyMeDmRXLyk=";
    };
    date = "2026-07-05";
  };
  acer-predator-turbo-rgb = {
    pname = "acer-predator-turbo-rgb";
    version = "6eafee25668cf2ffb8a79fd376a638e9ca4dc6db";
    src = fetchFromGitHub {
      owner = "JafarAkhondali";
      repo = "acer-predator-turbo-and-rgb-keyboard-linux-module";
      rev = "6eafee25668cf2ffb8a79fd376a638e9ca4dc6db";
      fetchSubmodules = false;
      sha256 = "sha256-TGBo9GxVJ74mOnqpkjZRFk0e7XiT6iZbVyMeDmRXLyk=";
    };
    date = "2026-07-05";
  };
  dopamine = {
    pname = "dopamine";
    version = "v3.0.7";
    src = fetchFromGitHub {
      owner = "digimezzo";
      repo = "dopamine";
      rev = "v3.0.7";
      fetchSubmodules = false;
      sha256 = "sha256-zYuf5BIQaxTqHBXWX1PLghGR5WmwtnSxTYrNosVFebc=";
    };
  };
  dw-proton = {
    pname = "dw-proton";
    version = "dwproton-11.0-5";
    src = fetchurl {
      url = "https://dawn.wine/dawn-winery/dwproton/releases/download/dwproton-11.0-5/dwproton-11.0-5-x86_64.tar.xz";
      sha256 = "sha256-GLXwUswB/uJEFWlij5KN9MUE483QOdvkTbKvEtk8VZI=";
    };
  };
  excalibur-wmi = {
    pname = "excalibur-wmi";
    version = "99bd638f167a0f72f3a3a7a60fe3a252dd388402";
    src = fetchFromGitHub {
      owner = "betelqeyza";
      repo = "excalibur-wmi";
      rev = "99bd638f167a0f72f3a3a7a60fe3a252dd388402";
      fetchSubmodules = false;
      sha256 = "sha256-qfwJn6JEe2GFaSluaS0sK69O8nh2SoQH+XvBDMElKec=";
    };
    date = "2026-02-13";
  };
  gecit = {
    pname = "gecit";
    version = "c35311483840f82f2b565238c4c120e77ae69b3d";
    src = fetchFromGitHub {
      owner = "boratanrikulu";
      repo = "gecit";
      rev = "c35311483840f82f2b565238c4c120e77ae69b3d";
      fetchSubmodules = false;
      sha256 = "sha256-aFcBV7a2Oe7TP+e5UTj/wof/fVGzOfOVFwBkjx7ccXo=";
    };
    date = "2026-05-13";
  };
  gobee = {
    pname = "gobee";
    version = "1a66b6012aa6996471e831b4e991bbea98d26f5f";
    src = fetchFromGitHub {
      owner = "boratanrikulu";
      repo = "gobee";
      rev = "1a66b6012aa6996471e831b4e991bbea98d26f5f";
      fetchSubmodules = false;
      sha256 = "sha256-p1TZQqji6JWqepdsul9lhOE4HHqt0jT9ug6pbzAJRBw=";
    };
    date = "2026-05-04";
  };
  hp-omen-wmi = {
    pname = "hp-omen-wmi";
    version = "a2d79368bf981a3f241a36941aaa4a7fe657d924";
    src = fetchFromGitHub {
      owner = "ranisalt";
      repo = "hp-omen-linux-module";
      rev = "a2d79368bf981a3f241a36941aaa4a7fe657d924";
      fetchSubmodules = false;
      sha256 = "sha256-fjxVezZ+hWsCA5iz9lOIXl3NHpCoDkoYWXa4qzs1Z6g=";
    };
    date = "2024-05-04";
  };
  hp-wmi-fan-and-backlight-control = {
    pname = "hp-wmi-fan-and-backlight-control";
    version = "eee2d0a06d01167c0faddf1d7cf30ad4c0f195fa";
    src = fetchFromGitHub {
      owner = "TUXOV";
      repo = "hp-wmi-fan-and-backlight-control";
      rev = "eee2d0a06d01167c0faddf1d7cf30ad4c0f195fa";
      fetchSubmodules = false;
      sha256 = "sha256-t/1cJ2dq6rpM3w4bomrpvMTB8PVyAxkvxPEw8hLsVm0=";
    };
    date = "2026-03-05";
  };
  iloader = {
    pname = "iloader";
    version = "v2.2.6";
    src = fetchFromGitHub {
      owner = "nab138";
      repo = "iloader";
      rev = "v2.2.6";
      fetchSubmodules = false;
      sha256 = "sha256-zSl08bhJ/OrdcvvL1ciybxgnLqrg4IinmcGXrsPQYyQ=";
    };
  };
  jdownloader2 = {
    pname = "jdownloader2";
    version = "12 Jul 2026 17:41:20 GMT";
    src = fetchurl {
      url = "https://installer.jdownloader.org/JDownloader.jar";
      sha256 = "sha256-OIodAo5ly8Y5M6d43bySZ8FOfnhYOJzjGhC+cwit60A=";
    };
  };
  nero-umu = {
    pname = "nero-umu";
    version = "f7f6d2b33d79f66deb942e6acfb1a225bdbc2ef8";
    src = fetchFromGitHub {
      owner = "SeongGino";
      repo = "Nero-umu";
      rev = "f7f6d2b33d79f66deb942e6acfb1a225bdbc2ef8";
      fetchSubmodules = false;
      sha256 = "sha256-HSKCILSuNxzK6UZX7bS5zms6b6iq9/+Fq7+D/qN3kXE=";
    };
    date = "2026-06-12";
  };
  omenrgb = {
    pname = "omenrgb";
    version = "f5041e1e357caaf3eb24030757e58066ea28725e";
    src = fetchFromGitHub {
      owner = "lemogne";
      repo = "omenrgb";
      rev = "f5041e1e357caaf3eb24030757e58066ea28725e";
      fetchSubmodules = false;
      sha256 = "sha256-4Pynz0QBixMfnFaYeYD2k9pZzwbqx6iBzUTW/M9eOaE=";
    };
    date = "2026-06-16";
  };
  proton-cachyos-x86_64-v3 = {
    pname = "proton-cachyos-x86_64-v3";
    version = "cachyos-11.0-20260702-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260702-slr/proton-cachyos-11.0-20260702-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-ETl4U+uV+PtEhTXOviZVRxMGyAw0VsRrUs1Whwik/lw=";
    };
  };
  seanime = {
    pname = "seanime";
    version = "v3.9.1";
    src = fetchFromGitHub {
      owner = "5rahim";
      repo = "seanime";
      rev = "v3.9.1";
      fetchSubmodules = false;
      sha256 = "sha256-T4TLQ3wMvUFURu5rDfUDWfnhSsmYWq4GGQBZvAd2ivs=";
    };
  };
  seanime-bin-canary = {
    pname = "seanime-bin-canary";
    version = "3.9.2-alpha.15";
    src = fetchurl {
      url = "https://seanime.app/api/updates/nightly/seanime-denshi-3.9.2-alpha.15_Linux_x86_64.AppImage";
      sha256 = "sha256-ezMGERVYze0YozzRGXKI7md/Dfz9sYMyRDfgiRHyXVM=";
    };
  };
  seanime-canary = {
    pname = "seanime-canary";
    version = "6b07e3a777e3fd49fb13258f0f01ddd0135cf5ff";
    src = fetchFromGitHub {
      owner = "5rahim";
      repo = "seanime";
      rev = "6b07e3a777e3fd49fb13258f0f01ddd0135cf5ff";
      fetchSubmodules = false;
      sha256 = "sha256-FG9qlx5wWarO+u9fxvrXLCdXj1kv1rxUAWhMP7ukB+0=";
    };
    date = "2026-07-11";
  };
  victus-control = {
    pname = "victus-control";
    version = "3cf7d22921a24adb7fe6e806c912679ef81f8c77";
    src = fetchFromGitHub {
      owner = "Vilez0";
      repo = "victus-control";
      rev = "3cf7d22921a24adb7fe6e806c912679ef81f8c77";
      fetchSubmodules = false;
      sha256 = "sha256-vpRbDA8gfCDx9NJX4EVqPWa49RAU73ZpHu4Y14C6CvQ=";
    };
    date = "2025-12-12";
  };
}
