# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  acer-predator-turbo-and-rgb-keyboard-linux-module = {
    pname = "acer-predator-turbo-and-rgb-keyboard-linux-module";
    version = "49d1d7d1e45755d3cf57e6b438620ec5bfdf0e4d";
    src = fetchFromGitHub {
      owner = "JafarAkhondali";
      repo = "acer-predator-turbo-and-rgb-keyboard-linux-module";
      rev = "49d1d7d1e45755d3cf57e6b438620ec5bfdf0e4d";
      fetchSubmodules = false;
      sha256 = "sha256-1yZVnN/Sru8qRNf1MN1Jt8PcjxYl8MOYxAFvpgZWj4E=";
    };
    date = "2026-01-27";
  };
  acer-predator-turbo-rgb = {
    pname = "acer-predator-turbo-rgb";
    version = "49d1d7d1e45755d3cf57e6b438620ec5bfdf0e4d";
    src = fetchFromGitHub {
      owner = "JafarAkhondali";
      repo = "acer-predator-turbo-and-rgb-keyboard-linux-module";
      rev = "49d1d7d1e45755d3cf57e6b438620ec5bfdf0e4d";
      fetchSubmodules = false;
      sha256 = "sha256-1yZVnN/Sru8qRNf1MN1Jt8PcjxYl8MOYxAFvpgZWj4E=";
    };
    date = "2026-01-27";
  };
  dopamine = {
    pname = "dopamine";
    version = "v3.0.5";
    src = fetchFromGitHub {
      owner = "digimezzo";
      repo = "dopamine";
      rev = "v3.0.5";
      fetchSubmodules = false;
      sha256 = "sha256-DfDH+6kIKbdz2pF7/3GixJdSWHAdUY2FhkG2GZRMyrY=";
    };
  };
  dw-proton = {
    pname = "dw-proton";
    version = "dwproton-11.0-3";
    src = fetchurl {
      url = "https://dawn.wine/dawn-winery/dwproton/releases/download/dwproton-11.0-3/dwproton-11.0-3-x86_64.tar.xz";
      sha256 = "sha256-w72OsYk/M+FeMMVy/166SqEERqGoh1Ax6NDnp+Dw9iQ=";
    };
  };
  excalibur-wmi = {
    pname = "excalibur-wmi";
    version = "99bd638f167a0f72f3a3a7a60fe3a252dd388402";
    src = fetchFromGitHub {
      owner = "betelqeyza";
      repo = "excalibur-wmi";
      rev = "99bd638f167a0f72f3a3a7a60fe3a252dd388402";
      fetchSubmodules = false;
      sha256 = "sha256-qfwJn6JEe2GFaSluaS0sK69O8nh2SoQH+XvBDMElKec=";
    };
    date = "2026-02-13";
  };
  gecit = {
    pname = "gecit";
    version = "c35311483840f82f2b565238c4c120e77ae69b3d";
    src = fetchFromGitHub {
      owner = "boratanrikulu";
      repo = "gecit";
      rev = "c35311483840f82f2b565238c4c120e77ae69b3d";
      fetchSubmodules = false;
      sha256 = "sha256-aFcBV7a2Oe7TP+e5UTj/wof/fVGzOfOVFwBkjx7ccXo=";
    };
    date = "2026-05-13";
  };
  gobee = {
    pname = "gobee";
    version = "1a66b6012aa6996471e831b4e991bbea98d26f5f";
    src = fetchFromGitHub {
      owner = "boratanrikulu";
      repo = "gobee";
      rev = "1a66b6012aa6996471e831b4e991bbea98d26f5f";
      fetchSubmodules = false;
      sha256 = "sha256-p1TZQqji6JWqepdsul9lhOE4HHqt0jT9ug6pbzAJRBw=";
    };
    date = "2026-05-04";
  };
  hp-omen-wmi = {
    pname = "hp-omen-wmi";
    version = "a2d79368bf981a3f241a36941aaa4a7fe657d924";
    src = fetchFromGitHub {
      owner = "ranisalt";
      repo = "hp-omen-linux-module";
      rev = "a2d79368bf981a3f241a36941aaa4a7fe657d924";
      fetchSubmodules = false;
      sha256 = "sha256-fjxVezZ+hWsCA5iz9lOIXl3NHpCoDkoYWXa4qzs1Z6g=";
    };
    date = "2024-05-04";
  };
  hp-wmi-fan-and-backlight-control = {
    pname = "hp-wmi-fan-and-backlight-control";
    version = "eee2d0a06d01167c0faddf1d7cf30ad4c0f195fa";
    src = fetchFromGitHub {
      owner = "TUXOV";
      repo = "hp-wmi-fan-and-backlight-control";
      rev = "eee2d0a06d01167c0faddf1d7cf30ad4c0f195fa";
      fetchSubmodules = false;
      sha256 = "sha256-t/1cJ2dq6rpM3w4bomrpvMTB8PVyAxkvxPEw8hLsVm0=";
    };
    date = "2026-03-05";
  };
  iloader = {
    pname = "iloader";
    version = "v2.2.6";
    src = fetchFromGitHub {
      owner = "nab138";
      repo = "iloader";
      rev = "v2.2.6";
      fetchSubmodules = false;
      sha256 = "sha256-zSl08bhJ/OrdcvvL1ciybxgnLqrg4IinmcGXrsPQYyQ=";
    };
  };
  jdownloader2 = {
    pname = "jdownloader2";
    version = "08 Jun 2026 06:44:44 GMT";
    src = fetchurl {
      url = "https://installer.jdownloader.org/JDownloader.jar";
      sha256 = "sha256-OIodAo5ly8Y5M6d43bySZ8FOfnhYOJzjGhC+cwit60A=";
    };
  };
  nero-umu = {
    pname = "nero-umu";
    version = "6246d8d2d01426c55311d5e02bd55b34d5818524";
    src = fetchFromGitHub {
      owner = "SeongGino";
      repo = "Nero-umu";
      rev = "6246d8d2d01426c55311d5e02bd55b34d5818524";
      fetchSubmodules = false;
      sha256 = "sha256-j6JS1r7LrhYBuENpuJQxgW8PPME2XmJveTb57svYdEs=";
    };
    date = "2026-02-23";
  };
  omenrgb = {
    pname = "omenrgb";
    version = "5b735ab3724aa6c9b88f82755f5e8a69ae908c32";
    src = fetchFromGitHub {
      owner = "lemogne";
      repo = "omenrgb";
      rev = "5b735ab3724aa6c9b88f82755f5e8a69ae908c32";
      fetchSubmodules = false;
      sha256 = "sha256-Eo2ovH5JB2eWWdfQg0O9clB7e/PxIjbuCxCm9gG0aiQ=";
    };
    date = "2026-06-07";
  };
  proton-cachyos-x86_64-v3 = {
    pname = "proton-cachyos-x86_64-v3";
    version = "cachyos-11.0-20260521-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20260521-slr/proton-cachyos-11.0-20260521-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-hWkZ+22va9Icx8DEj80k3lZId/jv/ETxXmB8UdwIz6U=";
    };
  };
  seanime = {
    pname = "seanime";
    version = "v3.8.4";
    src = fetchFromGitHub {
      owner = "5rahim";
      repo = "seanime";
      rev = "v3.8.4";
      fetchSubmodules = false;
      sha256 = "sha256-Sfd+HF+Of+dDFmK7v2D05ZxffEzu/m6N31ScEklA2ZM=";
    };
  };
  victus-control = {
    pname = "victus-control";
    version = "3cf7d22921a24adb7fe6e806c912679ef81f8c77";
    src = fetchFromGitHub {
      owner = "Vilez0";
      repo = "victus-control";
      rev = "3cf7d22921a24adb7fe6e806c912679ef81f8c77";
      fetchSubmodules = false;
      sha256 = "sha256-vpRbDA8gfCDx9NJX4EVqPWa49RAU73ZpHu4Y14C6CvQ=";
    };
    date = "2025-12-12";
  };
}
