# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  acer-predator-turbo-and-rgb-keyboard-linux-module = {
    pname = "acer-predator-turbo-and-rgb-keyboard-linux-module";
    version = "49d1d7d1e45755d3cf57e6b438620ec5bfdf0e4d";
    src = fetchFromGitHub {
      owner = "JafarAkhondali";
      repo = "acer-predator-turbo-and-rgb-keyboard-linux-module";
      rev = "49d1d7d1e45755d3cf57e6b438620ec5bfdf0e4d";
      fetchSubmodules = false;
      sha256 = "sha256-1yZVnN/Sru8qRNf1MN1Jt8PcjxYl8MOYxAFvpgZWj4E=";
    };
    date = "2026-01-27";
  };
  acer-predator-turbo-rgb = {
    pname = "acer-predator-turbo-rgb";
    version = "49d1d7d1e45755d3cf57e6b438620ec5bfdf0e4d";
    src = fetchFromGitHub {
      owner = "JafarAkhondali";
      repo = "acer-predator-turbo-and-rgb-keyboard-linux-module";
      rev = "49d1d7d1e45755d3cf57e6b438620ec5bfdf0e4d";
      fetchSubmodules = false;
      sha256 = "sha256-1yZVnN/Sru8qRNf1MN1Jt8PcjxYl8MOYxAFvpgZWj4E=";
    };
    date = "2026-01-27";
  };
  dopamine = {
    pname = "dopamine";
    version = "3.0.4";
    src = fetchurl {
      url = "https://github.com/digimezzo/dopamine/releases/download/v3.0.4/Dopamine-3.0.4.AppImage";
      sha256 = "sha256-sm8/ZzSqa1CsQJ7XfQ67yAKX5rR9E8J/Z6v1rLVhNwI=";
    };
  };
  excalibur-wmi = {
    pname = "excalibur-wmi";
    version = "99bd638f167a0f72f3a3a7a60fe3a252dd388402";
    src = fetchFromGitHub {
      owner = "betelqeyza";
      repo = "excalibur-wmi";
      rev = "99bd638f167a0f72f3a3a7a60fe3a252dd388402";
      fetchSubmodules = false;
      sha256 = "sha256-qfwJn6JEe2GFaSluaS0sK69O8nh2SoQH+XvBDMElKec=";
    };
    date = "2026-02-13";
  };
  gecit = {
    pname = "gecit";
    version = "d9c205bf016519b03fd55ab37a65ec2d84c46254";
    src = fetchFromGitHub {
      owner = "boratanrikulu";
      repo = "gecit";
      rev = "d9c205bf016519b03fd55ab37a65ec2d84c46254";
      fetchSubmodules = false;
      sha256 = "sha256-IJvMAFNpKuPlBPqFS6PCpSYRzjxNUEpw3YXpZ5t9lG8=";
    };
    date = "2026-04-21";
  };
  hp-omen-wmi = {
    pname = "hp-omen-wmi";
    version = "a2d79368bf981a3f241a36941aaa4a7fe657d924";
    src = fetchFromGitHub {
      owner = "ranisalt";
      repo = "hp-omen-linux-module";
      rev = "a2d79368bf981a3f241a36941aaa4a7fe657d924";
      fetchSubmodules = false;
      sha256 = "sha256-fjxVezZ+hWsCA5iz9lOIXl3NHpCoDkoYWXa4qzs1Z6g=";
    };
    date = "2024-05-04";
  };
  hp-wmi-fan-and-backlight-control = {
    pname = "hp-wmi-fan-and-backlight-control";
    version = "eee2d0a06d01167c0faddf1d7cf30ad4c0f195fa";
    src = fetchFromGitHub {
      owner = "TUXOV";
      repo = "hp-wmi-fan-and-backlight-control";
      rev = "eee2d0a06d01167c0faddf1d7cf30ad4c0f195fa";
      fetchSubmodules = false;
      sha256 = "sha256-t/1cJ2dq6rpM3w4bomrpvMTB8PVyAxkvxPEw8hLsVm0=";
    };
    date = "2026-03-05";
  };
  iloader = {
    pname = "iloader";
    version = "v2.2.4";
    src = fetchFromGitHub {
      owner = "nab138";
      repo = "iloader";
      rev = "v2.2.4";
      fetchSubmodules = false;
      sha256 = "sha256-cKUyxNsnqG1GSD+zMNjIoOkl4+IHRfWLQQo8IDjIS/o=";
    };
  };
  jdownloader2 = {
    pname = "jdownloader2";
    version = "21 Apr 2026 13:04:44 GMT";
    src = fetchurl {
      url = "https://installer.jdownloader.org/JDownloader.jar";
      sha256 = "sha256-OIodAo5ly8Y5M6d43bySZ8FOfnhYOJzjGhC+cwit60A=";
    };
  };
  nero-umu = {
    pname = "nero-umu";
    version = "6246d8d2d01426c55311d5e02bd55b34d5818524";
    src = fetchFromGitHub {
      owner = "SeongGino";
      repo = "Nero-umu";
      rev = "6246d8d2d01426c55311d5e02bd55b34d5818524";
      fetchSubmodules = false;
      sha256 = "sha256-j6JS1r7LrhYBuENpuJQxgW8PPME2XmJveTb57svYdEs=";
    };
    date = "2026-02-23";
  };
  omenrgb = {
    pname = "omenrgb";
    version = "5b68bc0a299df8926a03cded868766cc95ba644f";
    src = fetchFromGitHub {
      owner = "lemogne";
      repo = "omenrgb";
      rev = "5b68bc0a299df8926a03cded868766cc95ba644f";
      fetchSubmodules = false;
      sha256 = "sha256-lIr0Er4kt4UKeqg8smroBZ7ToOywP8C80+eIgGs3tWg=";
    };
    date = "2025-03-01";
  };
  proton-cachyos-x86_64-v3 = {
    pname = "proton-cachyos-x86_64-v3";
    version = "cachyos-10.0-20260410-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-10.0-20260410-slr/proton-cachyos-10.0-20260410-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-vJipf1yacr98lu7IkoZCg/563fvCp1x/8Nolyoj23SI=";
    };
  };
  seanime = {
    pname = "seanime";
    version = "v3.6.1";
    src = fetchFromGitHub {
      owner = "5rahim";
      repo = "seanime";
      rev = "v3.6.1";
      fetchSubmodules = false;
      sha256 = "sha256-utKOewhtuivkp0mtns2ysp+q0nwou7tojZ6VjrPhEMw=";
    };
  };
  seanime-denshi = {
    pname = "seanime-denshi";
    version = "3.6.1";
    src = fetchurl {
      url = "https://github.com/5rahim/seanime/releases/download/v3.6.1/seanime-denshi-3.6.1_Linux_x86_64.AppImage";
      sha256 = "sha256-hr2T6Lyf1QhYK1fb0Uy3Kj13j/rWfyCti32f335n2nA=";
    };
  };
  victus-control = {
    pname = "victus-control";
    version = "3cf7d22921a24adb7fe6e806c912679ef81f8c77";
    src = fetchFromGitHub {
      owner = "Vilez0";
      repo = "victus-control";
      rev = "3cf7d22921a24adb7fe6e806c912679ef81f8c77";
      fetchSubmodules = false;
      sha256 = "sha256-vpRbDA8gfCDx9NJX4EVqPWa49RAU73ZpHu4Y14C6CvQ=";
    };
    date = "2025-12-12";
  };
}
